alter_response: acqfs.random_edit_seq
batch_size: 2
discount_reward_factor: 0.95
gradient_accumulation_steps: 1
gradient_checkpointing: true
learning_rate: 0.0001
lora_alpha: 16
lora_dropout: 0.1
lora_r: 8
lora_target_modules:
- q_proj
- v_proj
max_new_tokens: 1024
max_rollout_retry: 32
mini_batch_size: 1
model_name_or_path: ckpts/HES-TS-AM-10-10seq/sft_model
output_dir: ckpts/HES-TS-AM-10-10seq/0
ppo_epochs: 4
query_dataset: data/ppo_2024-09-11T23:27:51.882496
reward_model: http://localhost:8000
save_steps: 1000
use_peft: true
verify_rollout: acqfs.spotlight_cost_fn
