bf16: true
dataset_name: placeholder
dataset_test_split: test
dataset_text_field: text
dataset_train_split: train
ddp_timeout: 180000000
gradient_accumulation_steps: 1
gradient_checkpointing: true
learning_rate: 0.0001
logging_steps: 1
lr_scheduler_type: cosine
model_name_or_path: meta-llama/Meta-Llama-3.1-8B-Instruct
num_train_epochs: 3.3
output_dir: saves/llama3-8b/sft/lora
overwrite_output_dir: true
per_device_train_batch_size: 4
report_to: none
save_steps: 500
warmup_ratio: 0.1
use_peft: true
lora_alpha: 32
lora_r: 16
lora_dropout: 0.1
lora_target_modules: ["q_proj", "v_proj"]