bf16: true
dataset_name: data/sft_2024-09-11T18:52:28.679900
dataset_test_split: test
dataset_text_field: text
dataset_train_split: train
ddp_timeout: 180000000
gradient_accumulation_steps: 1
gradient_checkpointing: true
learning_rate: 0.0001
logging_steps: 1
lora_alpha: 16
lora_dropout: 0.1
lora_r: 8
lora_target_modules:
- q_proj
- v_proj
lr_scheduler_type: cosine
model_name_or_path: meta-llama/Meta-Llama-3-8B-Instruct
num_train_epochs: 10.0
output_dir: ckpts/EI-10seq/sft_model
overwrite_output_dir: true
per_device_train_batch_size: 2
report_to: none
save_steps: 500
use_peft: true
warmup_ratio: 0.1
