PROTEINS = {
    "v1": {
        "POLICY_PROMPT": """Edit 1 amino acid in the below protein sequence to create a new protein with higher fluorescence. The amino acid must be in set {{D, E}}.
Protein sequence: {protein}
""",
        "INIT_SEQ": "SKGEELFTGVVPILVELGGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTLSYGVQCFSRFPDHMKQHDFFKSAMPEGYVQERTIFSKDDGNYKTRAEVKFEGDELVNRIELKGIDFKEEENILGHKLEENYNSHNVYIMADDQKNGIKVNFKIRHNIEDDSVQLADHYQQNTPIGDEPVLLPDDHYLSTQSALSKDDNEDRDEMVLLEFVTAAGITHGMDELYK",
        "MAX_SEQ": "SKGEELFTGVVPILVELGGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTLSYGVQCFSRFPDHMKQHDFFKSAMPEGYVQERTIFSKDDGNYKTRAEVKFEGDDLVNRIELKGIDFKEDDNILGHKLEDNYNSHNVYIMADEQKNGIKVNFKIRHNIEEESVQLADHYQQNTPIGDDPVLLPDEHYLSTQSALSKDENEERDDMVLLEFVTAAGITHGMDELYK",
        "ALLOWED_POS": [116, 131, 132, 141, 154, 171, 172, 189, 196, 209, 212, 215],
        "ALLOWED_TOKENS": [
            "E",
            "D",
        ],
    },
    "v2": {
        "POLICY_PROMPT": """Edit 1 amino acid in the below protein sequence to create a new protein with higher fluorescence. The amino acid must be in set {{G, P}}.
Protein sequence: {protein}
""",
        "INIT_SEQ": "SKPEELFTPVVGILVELDPDVNGHKFSVSGEGEPDATYGKLTLKFICTTGKLGVGWGTLVTTLSYGVQCFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEPDTLVNRIELKGIVFKEDGNTLGHKLEYNYNSHNVYIMADEQKNGIKVNFKIRHNIEDGSVQLADHYQQNTPIPDGPVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITHGMDELYK",
        "MAX_SEQ": "SKGEELFTGVVPILVELDGDVNGHKFSVSGEGEGDATYGKLTLKFICTTGKLPVPWPTLVTTLSYGVQCFSRYPDHMKQHDFFKSAMPEGYVQERTIFFKDDGNYKTRAEVKFEGDTLVNRIELKGIVFKEDGNTLGHKLEYNYNSHNVYIMADEQKNPIKVNFKIRHNIEDGSVQLADHYQQNTPIGDGGVLLPDNHYLSTQSALSKDPNEKRDHMVLLEFVTAAGITHGMDELYK",
        "ALLOWED_POS": [
            2,
            8,
            11,
            18,
            33,
            52,
            54,
            56,
            114,
            158,
            187,
            190,
        ],
        "ALLOWED_TOKENS": [
            "G",
            "P",
        ],
    },
}
